### ISSUE TITLE
Utilising Argparse more effectively

### ISSUE THREAD

**Issue by meta-l** [bharshbarger/AutOSINT#21]
Hey,

First off, I love this script idea. Bundling it all into one tool is a natural progression.

Got some ideas on this: For the 'required' arguments within argparse, could use the appropriate tag and do away with some of the if/else checks (and return requirement results on same screen rather than clearing the  terminal). 

Also could add mutually exclusive groups in for domain/IP address, should allow some more if statements to be removed.

Some more if/else statements could be re-purposed so that code flow is directed more efficiently - specifically the if statements checking for the command line switches in the checkargs function.

What do you think?

**Comment by bharshbarger** [comment]
Agree that the whole logic behind required args is...a mess. I'm still learning so it's definitely a limitation of my own knowledge.  If you have an example of a tag or groups, I'd be interested in improving it.

**Comment by meta-l** [comment]
I'm still learning too :)

Check out the python in a my 3 repos to see the argparse - slackwall has an example of mutually exclusive group, and htgrab has one with a required tag. Betrayal appears to be similar to an smb script you've written. Perhaps they could be combined somehow?

**Comment by bharshbarger** [comment]
leaving out IP in favor of searching for domains only. can re-add in later if need be
