### ISSUE TITLE
is reportgen working

### ISSUE THREAD

**Issue by meta-l** [bharshbarger/AutOSINT#23]
I can only get the script to output to the text files if an active module is chosen. Am I looking in the correct place?

**Comment by bharshbarger** [comment]
A docx should appear in the reports/<domain>/ directory where the text files appear. Even if no data you should get a boilerplate report. Definitely a problem if that's not happening.

**Comment by meta-l** [comment]
I'll check again tomorrow with all the switches, mostly concentrated on getting the hibp stuff working a bit better. Pretty sure it doesn't though - although could be a dependancy.

**Comment by meta-l** [comment]
Report is generated if I use googledork and pastebin scrapes. If I choose to use other modules (or not those) a report isn't generated.

**Comment by bharshbarger** [comment]
decided to simplify by just running all modules every time.
